spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: restaurant-events


  datasource:
    url: jdbc:postgresql://localhost:5432/restourant
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/01_restaurant.yml
    enabled: true

redis:
  server:
   url: redis://localhost:6379